


export const catchError(fun)=>{
    return (req)=>{}
}